language: generic
sudo: false
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=26
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
dist: trusty
addons:
  apt:
    packages:
      - texinfo
script:
  - make
  - make test
  - make info
before_deploy: cd doc && make doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: test-travis
    condition: $EMACS_VERSION = 26
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/848b93e13f8e6ab0cc86
    on_success: always
    on_failure: always
    on_start: always
  email:
    on_success: change
    on_failure: always
    on_start: never
